baseurl = "http://doorbash.ir/blog/"
languageCode = "en-us"
title = "بلاگ - میلاد دورباش"
theme = "hugo-cards"
paginate = 6

[params]
  parentName = "میلاد دورباش"
  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = "https://twitter.com/doorbash"
  github = "https://github.com/doorbash/blog.doorbash.ir"
  email = "milad.doorbash@gmail.com"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = "doorbash-ir"

  [params.copyright]
     name = "میلاد دورباش"
     link = "http://doorbash.ir"

