baseurl = "https://doorbash.github.io/blog/"
languageCode = "en-us"
title = "بلاگ - میلاد دورباش"
theme = "hugo-cards"
paginate = 6

#[markup.goldmark.renderer]
#unsafe= true

pygmentsCodefences = true
pygmentsStyle = "github"

[params]
  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = "https://www.facebook.com/milad.doorbash"
  quora = ""
  twitter = "https://twitter.com/doorbash"
  github = "https://github.com/doorbash/blog.doorbash.ir"
  email = "milad.doorbash@gmail.com"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = "UA-128176167-2"
  disqus = "doorbash-github-io"

  [params.copyright]
     name = "میلاد دورباش"
     link = "https://doorbash.github.io"

